# Generated by Django 3.0.5 on 2020-05-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20200503_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
