# Generated by Django 3.0.5 on 2020-05-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20200503_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
