# Generated by Django 3.0.5 on 2020-05-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_auto_20200525_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
